spring:
  application:
    name: container-yard-allocation-service
  datasource:
    url: jdbc:mysql://localhost:3307/container_yard_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8081